[profile.default]
solc-version = "0.8.17"
src = 'contracts'
out = 'out'
viaIR = true
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''




# See more config options https://github.com/foundry-rs/foundry/tree/master/config

