import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from 'antd';
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="Index">

          <div className="banner">
            <p className="banner-title">帮助你发现可信赖的开发者保障开发者的费用</p>
            <div className="banner-info">
              <Link href={{pathname:'/publish'}}>
                <Button className="btn">发布需求</Button>
              </Link>
              <Link href={{pathname:'/projects'}}>
                <Button className="btn">寻找项目</Button>
              </Link>
            </div>
          </div>

          <div className="data">
              <div className="data-li">
                <p className="title">社区成员</p>
                <p className="text">200W社区成员</p>
              </div>
              <div className="data-li">
                <p className="title">项目数量</p>
                <p className="text">xxx</p>
              </div>
              <div className="data-li">
                <p className="title">社区成员</p>
                <p className="text">200W社区成员</p>
              </div>
          </div>

          <div className="ucan">
            <p className="ucan-title font-Title">你可以</p>

            <div className="ucan-li">
              <div className="li-info">
                <p className="title">发布需求</p>
                <div className="content">
                  <p>发布项目需求，寻找可信赖的开发者。</p>
                  <p>在这里，通过开发者的NFT，评估开发者能力。</p>
                  <p>获得项目NFT，提高你的公信力。</p>
                </div>
                <Button className="btn">了解更多</Button>
              </div>
              <div className="li-img"></div>
            </div>

            <div className="ucan-li">
              <div className="li-img"></div>
              <div className="li-info">
                <p className="title">发布需求</p>
                <div className="content">
                  <p>发布项目需求，寻找可信赖的开发者。</p>
                  <p>在这里，通过开发者的NFT，评估开发者能力。</p>
                  <p>获得项目NFT，提高你的公信力。</p>
                </div>
                <Button className="btn">了解更多</Button>
              </div>
            </div>

          </div>

          <div className="introduction">
            <p className="introduction-title font-Title">
              信任工具
            </p>
            <div className="introduction-img">

            </div>
          </div>

          <div className="example">
            <p className="example-title font-Title">案例</p>
            <div className="example-list">
              <div className="example-li">
                <div className="li-img"></div>
                <div className="li-info">
                  <p className="title">项目名称</p>
                  <p className="subtitle">项目名称项目名称项目名称项目名称项目名称项目名称</p>
                  <Button className="btn">进入项目</Button>
                </div>
              </div>

              <div className="example-li">
                <div className="li-img"></div>
                <div className="li-info">
                  <p className="title">项目名称</p>
                  <p className="subtitle">项目名称项目名称项目名称项目名称项目名称项目名称</p>
                  <Button className="btn">进入项目</Button>
                </div>
              </div>

              <div className="example-li">
                <div className="li-img"></div>
                <div className="li-info">
                  <p className="title">项目名称</p>
                  <p className="subtitle">项目名称项目名称项目名称项目名称项目名称项目名称</p>
                  <Button className="btn">进入项目</Button>
                </div>
              </div>

              <div className="example-li">
                <div className="li-img"></div>
                <div className="li-info">
                  <p className="title">项目名称</p>
                  <p className="subtitle">项目名称项目名称项目名称项目名称项目名称项目名称</p>
                  <Button className="btn">进入项目</Button>
                </div>
              </div>
            </div>
            
          </div>

          <div className="h100"></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
