import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from 'antd';
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="Index">

          <div className="banner">
            <p className="banner-title">GUARANTEE THE DEVELOPER'S EXPENSES</p>
            <div className="banner-info">
              <Link href={{pathname:'/publish'}}>
                <Button className="btn">发布需求</Button>
              </Link>
              <Link href={{pathname:'/projects'}}>
                <Button className="btn">寻找项目</Button>
              </Link>
            </div>
          </div>

          <div className="data">
              <div className="data-li">
                <div className="img"></div>
                <p className="title">Reference project</p>
                <p className="text">Browse past project works, sort out complete project needs, or directly find professionals you can trust.</p>
              </div>
              <div className="data-li">
                <div className="img"></div>
                <p className="title">Smart contract</p>
                <p className="text">After confirming the cooperation, execute the smart contract, confirm the delivery of automatic payment, and reduce other transaction costs related to the contract.</p>
              </div>
              <div className="data-li">
                <div className="img"></div>
                <p className="title">NFT display</p>
                <p className="text">Each time the project is completed, NFTs are displayed on both sides. You can choose the people you trust by the number of NFTs displayed.</p>
              </div>
          </div>

          <div className="ucan">
            <div className="ucan-title">
              <div className="img"></div>
              <p className="font-Title">You can</p>
              <div className="point"/>
            </div>
            <div className="ucan-list">
              <div className="list-li">
                <div className="li-info">
                  <div className="img"></div>
                  <p className="title">Release requirements</p>
                  <div className="content">
                    <p>Release project requirements and find reliable developers。</p>
                    <p>Here, through the developer's NFT, evaluate the developer's ability。</p>
                    <p>Get project NFT and improve your credibility</p>
                  </div>
                  <Button className="btn">Learn more</Button>
                </div>
              </div>
              <div className="list-li">
                <div className="li-info">
                  <div className="img"></div>
                  <p className="title">Release requirements</p>
                  <div className="content">
                    <p>Release project requirements and find reliable developers。</p>
                    <p>Here, through the developer's NFT, evaluate the developer's ability。</p>
                    <p>Get project NFT and improve your credibility</p>
                  </div>
                  <Button className="btn">Learn more</Button>
                </div>
              </div>
            </div>
          </div>

          <div className="introduction">
            <p className="introduction-title font-Title">
              信任工具
            </p>
            <div className="introduction-img">

            </div>
          </div>

          <div className="example">
            <p className="example-title font-Title">案例</p>
            <div className="example-list">
              <div className="example-li">
                <div className="li-img"></div>
                <div className="li-info">
                  <p className="title">项目名称</p>
                  <p className="subtitle">项目名称项目名称项目名称项目名称项目名称项目名称</p>
                  <Button className="btn">进入项目</Button>
                </div>
              </div>

              <div className="example-li">
                <div className="li-img"></div>
                <div className="li-info">
                  <p className="title">项目名称</p>
                  <p className="subtitle">项目名称项目名称项目名称项目名称项目名称项目名称</p>
                  <Button className="btn">进入项目</Button>
                </div>
              </div>

              <div className="example-li">
                <div className="li-img"></div>
                <div className="li-info">
                  <p className="title">项目名称</p>
                  <p className="subtitle">项目名称项目名称项目名称项目名称项目名称项目名称</p>
                  <Button className="btn">进入项目</Button>
                </div>
              </div>

              <div className="example-li">
                <div className="li-img"></div>
                <div className="li-info">
                  <p className="title">项目名称</p>
                  <p className="subtitle">项目名称项目名称项目名称项目名称项目名称项目名称</p>
                  <Button className="btn">进入项目</Button>
                </div>
              </div>
            </div>
            
          </div>

          <div className="h100"></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
